-- Lista książek aktualnie wypożyczonych
SELECT 
    WYPOZYCZENIA.WYPOZYCZENIE_ID,
    CZYTELNICY.IMIE || ' ' || CZYTELNICY.NAZWISKO AS CZYTELNIK,
    KSIAZKI.TYTUL AS KSIAZKA,
    WYPOZYCZENIA.DATA_WYPOZYCZENIA,
    WYPOZYCZENIA.DATA_ZWROTU
FROM 
    WYPOZYCZENIA
JOIN 
    CZYTELNICY ON WYPOZYCZENIA.CZYTELNIK_ID = CZYTELNICY.CZYTELNIK_ID
JOIN 
    KSIAZKI ON WYPOZYCZENIA.KSIAZKA_ID = KSIAZKI.KSIAZKA_ID
WHERE 
    KSIAZKI.DOSTEPNOSC = 'N';

-- 16 najczęściej wypożyczanych książek w bibliotece

SELECT 
    KSIAZKI.TYTUL AS TYTUL_KSIAZKI,
    COUNT(WYPOZYCZENIA.KSIAZKA_ID) AS LICZBA_WYPOZYCZEN
FROM 
    WYPOZYCZENIA
JOIN 
    KSIAZKI ON WYPOZYCZENIA.KSIAZKA_ID = KSIAZKI.KSIAZKA_ID
GROUP BY 
    KSIAZKI.TYTUL
ORDER BY 
    COUNT(WYPOZYCZENIA.KSIAZKA_ID) DESC
FETCH FIRST 16 ROWS ONLY;


-- Lista książek przetrzymanych (od daty wypożyczenia minęło > 30 dni) wraz z danymi czytelników wypożyczających

SELECT 
    WYPOZYCZENIA.WYPOZYCZENIE_ID,
    CZYTELNICY.IMIE || ' ' || CZYTELNICY.NAZWISKO AS CZYTELNIK,
    KSIAZKI.TYTUL AS KSIAZKA,
    WYPOZYCZENIA.DATA_WYPOZYCZENIA
FROM 
    WYPOZYCZENIA
JOIN 
    CZYTELNICY ON WYPOZYCZENIA.CZYTELNIK_ID = CZYTELNICY.CZYTELNIK_ID
JOIN 
    KSIAZKI ON WYPOZYCZENIA.KSIAZKA_ID = KSIAZKI.KSIAZKA_ID
WHERE 
    WYPOZYCZENIA.DATA_ZWROTU > SYSDATE + 14;

-- Lista wszystkich książek autora o nazwisku YYYY

SELECT 
    KSIAZKI.TYTUL AS TYTUL_KSIAZKI,
    AUTORZY.IMIE || ' ' || AUTORZY.NAZWISKO AS AUTOR
FROM 
    KSIAZKI
JOIN 
    AUTORZY ON KSIAZKI.AUTOR_ID = AUTORZY.AUTOR_ID
WHERE 
    AUTORZY.NAZWISKO = 'Rowling';

-- Lista książek nigdy nie wypożyczonych

SELECT 
    KSIAZKI.TYTUL AS TYTUL_KSIAZKI
FROM 
    KSIAZKI
LEFT JOIN 
    WYPOZYCZENIA ON KSIAZKI.KSIAZKA_ID = WYPOZYCZENIA.KSIAZKA_ID
WHERE 
    WYPOZYCZENIA.KSIAZKA_ID IS NULL;


-- Lista czytelników, którzy w ciągu ostatniego roku wypożyczyli najwięcej książek

SELECT 
    CZYTELNICY.CZYTELNIK_ID,
    CZYTELNICY.IMIE || ' ' || CZYTELNICY.NAZWISKO AS CZYTELNIK,
    COUNT(WYPOZYCZENIA.WYPOZYCZENIE_ID) AS LICZBA_WYPOZYCZEN
FROM 
    CZYTELNICY
JOIN 
    WYPOZYCZENIA ON CZYTELNICY.CZYTELNIK_ID = WYPOZYCZENIA.CZYTELNIK_ID
WHERE 
    WYPOZYCZENIA.DATA_WYPOZYCZENIA >= TRUNC(SYSDATE, 'YYYY') - INTERVAL '1' YEAR
GROUP BY 
    CZYTELNICY.CZYTELNIK_ID,
    CZYTELNICY.IMIE,
    CZYTELNICY.NAZWISKO
ORDER BY 
    COUNT(WYPOZYCZENIA.WYPOZYCZENIE_ID) DESC
FETCH FIRST 10 ROWS ONLY;


